version: '3.9'
services:
  bid-service:
    build:
      context: .
      dockerfile: bid-service/Dockerfile
    ports:
      - "8087:8087"

  post-service:
    build:
      context: .
      dockerfile: post-service/Dockerfile
    ports:
      - "8081:8081"

  sms-service:
    build:
      context: .
      dockerfile: sms-service/Dockerfile
    ports:
      - "8086:8086"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8080:8080"

  jwt-service:
    build:
      context: .
      dockerfile: jwt-service/Dockerfile
    ports:
      - "8082:8082"

#written a docker-compose.yml so you can build and run all services at once.
#docker compose up --build